name: Capacitor Updates 2

on: repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Capacitor Update
        run: 'echo "field: ${{ github.event.client_payload.capacitor_version }}"'