name: CI

on:
  push:
    paths:
      - 'plugin/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'plugin/**'
      - '.github/workflows/ci.yml'
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v6
      - name: Get Latest
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: core/
  verify-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - setup
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm install
        working-directory: plugin
      - run: npm run build
        working-directory: plugin
