name: Pre-Release

on:
  push:
    branches:
      - "release/**"

permissions:
  contents: write

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Assign version from branch name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: plugin
        run: npm install

      - name: Bump npm package version
        working-directory: plugin
        run: npm version $RELEASE_VERSION --no-git-tag-version --allow-same-version

      - name: Commit version bump
        uses: EndBug/add-and-commit@v9
