name: Publish Carthage .xcframework

jobs:
  verify:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.0.app
      - uses: actions/checkout@v2
      - name: Install Cocoapods
        run: gem install cocoapods
      - run: pod install
        working-directory: ./ios
      - name: Install Carthage Packages
      - run: carthage bootstrap --use-xcframeworks
      - run: npm run verify
        working-directory: ./ios
  build-xcframework:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.0.app
      - uses: actions/checkout@v2
      - name: Install Cocoapods
        run: gem install cocoapods
      - run: pod install
        working-directory: ./ios
      - name: Install Carthage Packages
      - run: carthage bootstrap --use-xcframeworks
      - name: Build .xcframework.zip file
      - run: ./carthage.sh
  build:
    runs-on: macos-11
    needs:
      - build-xcframework
    steps:
      - name: Release Zip
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: IonicPortals.xcframework.zip
